### Pandas
- 리스트, numpy, csv등을 dataframe으로 변경 -> 데이터 가공,처리
- series : 컬럼 1개
- dataframe : 컬럼 여러개
- index : RDBMS의 PK같은 개념. 개별 데이터를 고유하게 식별하는 key값


In [3]:
import pandas as pd
import numpy as np

In [4]:
titanic_df = pd.read_csv('titanic_train.csv')
type(titanic_df)

pandas.core.frame.DataFrame

In [8]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
titanic_df.shape

(891, 12)

In [10]:
## R - str()
## 상세 정보조회
## Dtype - object : str
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [11]:
## R - summary()
## 숫자형에 대해서
## 50% : median
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
## R - table()
## .value_counts() : 빈도수
value_counts = titanic_df['Pclass'].value_counts()
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [13]:
## series : 컬럼 1개
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [17]:
## index
titanic_pclass.head(10)
titanic_pclass.tail(10)

881    3
882    3
883    2
884    3
885    3
886    2
887    1
888    3
889    1
890    3
Name: Pclass, dtype: int64

DataFrame, 리스트, 딕셔너리, numpy ndarray 상호변환

In [20]:
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print(array1.shape)

df_list1 = pd.DataFrame(list1, columns=col_name1)
print(df_list1)

df_list2 = pd.DataFrame(array1, columns = col_name1)
print(df_list2)

(3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3


In [23]:
col_name2 = ['col1','col2','col3']
list2 = [[1,2,3],[11,12,13]]
array2 = np.array(list2)
print(array2.shape)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print(type(df_list2))

df_array2 = pd.DataFrame(array2, columns = col_name2)
print(type(df_array2))

(2, 3)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [31]:
dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print(df_dict)
print(df_dict.values)

   col1  col2  col3
0     1     2     3
1    11    22    33
[[ 1  2  3]
 [11 22 33]]


In [28]:
## dataframe -> numpy, list, dict
array3 = df_dict.values
print(type(array3), array3.shape)
print(array3)

<class 'numpy.ndarray'> (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [29]:
## dataframe -> list
list3 = df_dict.values.tolist()
print(type(list3))
print(list3)

<class 'list'>
[[1, 2, 3], [11, 22, 33]]


In [30]:
## dataframe -> dict
dict3 = df_dict.to_dict('list')
print(type(dict3))
print(dict3)

<class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


### dataframe 컬럼 데이터셋 접근

In [34]:
## 새로운 컬럼 추가 및 초기화
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [37]:
titanic_df['Age_10'] = titanic_df['Age']*10
## 가족수
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      0   220.0          1  
1      0          PC 17599  71.2833   C85        C      0   380.0          1  
2      0  STON/O2. 3101282   7.9250   NaN        S      0   260.0          0

In [38]:
titanic_df['Age_10'] = titanic_df['Age_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      0   320.0          1  
1      0          PC 17599  71.2833   C85        C      0   480.0          1  
2      0  STON/O2. 3101282   7.9250   NaN        S      0   360.0          0

In [40]:
## dataframe 데이터 삭제
## 컬럼 삭제 => 컬럼방향, axis=1
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S   320.0          1  
1      0          PC 17599  71.2833   C85        C   480.0          1  
2      0  STON/O2. 3101282   7.9250   NaN        S   360.0          0

In [41]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      0   320.0          1  
1      0          PC 17599  71.2833   C85        C      0   480.0          1  
2      0  STON/O2. 3101282   7.9250   NaN        S      0   360.0          0

In [42]:
## inplace = True : 원본까지 바뀜
## default : 원본은 안바뀜.
drop_result = titanic_df.drop(['Age_0', 'Age_10', 'Family_No'], axis=1, inplace=True)
print(drop_result)
titanic_df.head(3)

None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [45]:
titanic_df.drop([0,1,2], axis=0, inplace = True)
print(titanic_df.head(3))

   PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

   Ticket     Fare Cabin Embarked  
3  113803  53.1000  C123        S  
4  373450   8.0500   NaN        S  
5  330877   8.4583   NaN        Q  


Index 객체  -> dataframe.index, Series.index

In [60]:
print(titanic_df.head(3))
indexes = titanic_df.index

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  


In [61]:
print(indexes)

RangeIndex(start=0, stop=891, step=1)


In [64]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [65]:
## 값 변경 불가.
indexes[0] = 5

TypeError: Index does not support mutable operations

In [68]:
series_fair = titanic_df['Fare']
print(series_fair)
print(series_fair.max())
print(series_fair.sum())
print((series_fair + 3).head(3))

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64
512.3292
28693.9493
0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [71]:
## reset_index() : index 새로 생성
## 기존 index 삭제시 : drop = True
## inplace = True : 원본에 변경을 적용함. 대부분 메서드에 적용됨.
titanic_reset_df = titanic_df.reset_index(drop = True)
titanic_reset_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [73]:
value_counts = titanic_df['Pclass'].value_counts()

print(value_counts)
print(type(value_counts))

new_val_counts = value_counts.reset_index()
print(new_val_counts)
print(type(new_val_counts))

3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>
   index  Pclass
0      3     491
1      1     216
2      2     184
<class 'pandas.core.frame.DataFrame'>


데이터 셀렉션 및 필터링

In [74]:
titanic_df['Pclass'].head(3)

0    3
1    1
2    3
Name: Pclass, dtype: int64

In [75]:
## column 으로 셀렉션
titanic_df[['Survived', 'Pclass']].head(3)

Survived  Pclass
0         0       3
1         1       1
2         1       3

In [76]:
## row 로 셀렉션
titanic_df[0:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [78]:
## 조건으로 셀렉션
len(titanic_df[titanic_df['Pclass'] == 3])

491

In [82]:
## dataframe ix[] 연산자로 셀렉션
titanic_df.ix[0,2]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [83]:
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [89]:
data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns={'index':'old_index'})

data_df_reset.index = data_df_reset.index + 1
data_df_reset

old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [88]:
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [87]:
## iloc : 수치 기반 인덱싱 => 자동 생성된 인덱스만. 변경하면 loc 사용
## loc : 명칭 기반 인덱싱
data_df.iloc[0,0]

'Chulmin'

In [90]:
data_df_reset.iloc[0,1]

'Chulmin'

In [91]:
data_df.loc['one', 'Name']

'Chulmin'

In [93]:
data_df_reset.loc[1, 'Name']

'Chulmin'

In [94]:
## iloc :  0:1에서 1은 포함안함.
data_df.iloc[0:1, 0]

one    Chulmin
Name: Name, dtype: object

In [96]:
## loc : one, two 다 포함.
data_df.loc['one':'two', 'Name']

one     Chulmin
two    Eunkyung
Name: Name, dtype: object

In [98]:
data_df_reset.loc[1:2, 'Year']

1    2011
2    2016
Name: Year, dtype: int64

In [2]:
titanic_df = pd.read_csv('titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age'] > 60 ]
print(len(titanic_boolean))

NameError: name 'pd' is not defined

In [102]:
titanic_df[titanic_df['Age'] > 60][['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [103]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [104]:
titanic_df[(titanic_df['Age'] > 60) & (titanic_df['Pclass'] == 1) & (titanic_df['Sex'] == 'female')]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [105]:
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'
titanic_df[cond1 & cond2 & cond3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

#### 정렬, Aggregation, group by

In [106]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [108]:
titanic_sorted = titanic_df.sort_values(by = ['Name'])
titanic_sorted.tail(3)

PassengerId  Survived  Pclass                             Name   Sex  \
361          362         0       2        del Carlo, Mr. Sebastiano  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
868          869         0       3      van Melkebeke, Mr. Philemon  male   

      Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
361  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
153  40.5      0      2       A/5. 851  14.5000   NaN        S  
868   NaN      0      0         345777   9.5000   NaN        S

In [109]:
titanic_sorted = titanic_df.sort_values(by = ['Pclass', 'Name'], ascending = False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
282          283         0       3        de Pelsmaeker, Mr. Alfons  male   

      Age  SibSp  Parch    Ticket  Fare Cabin Embarked  
868   NaN      0      0    345777   9.5   NaN        S  
153  40.5      0      2  A/5. 851  14.5   NaN        S  
282  16.0      0      0    345778   9.5   NaN        S

In [110]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [111]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [114]:
titanic_groupby = titanic_df.groupby(by = 'Pclass')
titanic_groupby.mean()

PassengerId  Survived        Age     SibSp     Parch       Fare
Pclass                                                                 
1        461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
2        445.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3        439.154786  0.242363  25.140620  0.615071  0.393075  13.675550

In [116]:
titanic_df.groupby('Pclass') [['PassengerId', 'Survived']].count()

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [117]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [118]:
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 결손 데이터 처리하기

In [5]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

In [6]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
## fillna('값', inplace = True)
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

In [8]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [9]:
def get_square(a) :
    return a**2
print(get_square(3))

9


In [10]:
lambda_square = lambda x: x**2
print(lambda_square(3))

9


In [11]:
a=[1,2,3]
squares = map(lambda x: x**2, a)
list(squares)

[1, 4, 9]

In [13]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name','Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [14]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x: 'Child'
                                                   if x <=15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child